version: '3.7'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  # PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets.json:/etc/prometheus/targets.json
      # - ./prometheus/targets.yaml:/etc/prometheus/targets.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring
  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./blackbox/config.yml:/etc/blackbox/blackbox.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
    expose:
      - 9115
    networks:
      - monitoring
    # speedtest-exporter:
    #   image: miguelndecarvalho/speedtest-exporter
    #   container_name: speedtest-exporter
    #   environment:
    #     - SPEEDTEST_SERVER=<server-id> #optional
    #   ports:
    #     - 9798:9798
    #   restart: unless-stopped
    #   networks:
    #     - monitoring
